-- Create the discord_users table
CREATE TABLE IF NOT EXISTS discord_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    discord_id TEXT UNIQUE NOT NULL,
    username TEXT NOT NULL,
    discriminator TEXT,
    email TEXT,
    avatar TEXT,
    access_token TEXT,
    refresh_token TEXT,
    token_expires_at TIMESTAMPTZ,
    is_admin BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now(),
    last_login TIMESTAMPTZ DEFAULT now()
);

-- Create the flight_plans_received table
CREATE TABLE IF NOT EXISTS flight_plans_received (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now(),
    callsign TEXT,
    aircraft TEXT,
    departing TEXT,
    arriving TEXT,
    route TEXT,
    flightlevel TEXT,
    flightrules TEXT,
    source TEXT,
    timestamp DOUBLE PRECISION
);

-- Create the clearance_generations table
CREATE TABLE IF NOT EXISTS clearance_generations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now(),
    ip_address TEXT,
    user_agent TEXT,
    user_id UUID REFERENCES discord_users(id),
    callsign TEXT,
    destination TEXT,
    route TEXT,
    routing_type TEXT,
    runway TEXT,
    initial_altitude INTEGER,
    station TEXT,
    atis_info TEXT,
    clearance_text TEXT,
    discord_username TEXT
);

-- Create the upsert_discord_user function
CREATE OR REPLACE FUNCTION upsert_discord_user(
    p_discord_id text,
    p_username text,
    p_discriminator text,
    p_email text,
    p_avatar text,
    p_access_token text,
    p_refresh_token text,
    p_token_expires_at text
)
RETURNS TABLE(id uuid, discord_id text, username text, avatar text, is_admin boolean) AS $$
BEGIN
    RETURN QUERY
    INSERT INTO discord_users (discord_id, username, discriminator, email, avatar, access_token, refresh_token, token_expires_at, last_login)
    VALUES (p_discord_id, p_username, p_discriminator, p_email, p_avatar, p_access_token, p_refresh_token, to_timestamp(p_token_expires_at::bigint), now())
    ON CONFLICT (discord_id) DO UPDATE
    SET
        username = p_username,
        discriminator = p_discriminator,
        email = p_email,
        avatar = p_avatar,
        access_token = p_access_token,
        refresh_token = p_refresh_token,
        token_expires_at = to_timestamp(p_token_expires_at::bigint),
        last_login = now()
    RETURNING discord_users.id, discord_users.discord_id, discord_users.username, discord_users.avatar, discord_users.is_admin;
END;
$$ LANGUAGE plpgsql;

-- Create the get_clearance_leaderboard function
CREATE OR REPLACE FUNCTION get_clearance_leaderboard()
RETURNS TABLE(rank bigint, avatar text, username text, clearance_count bigint) AS $$
BEGIN
    RETURN QUERY
    SELECT
        ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC) as rank,
        du.avatar,
        du.username,
        COUNT(*) as clearance_count
    FROM
        clearance_generations cg
    JOIN
        discord_users du ON cg.user_id = du.id
    GROUP BY
        du.id, du.username, du.avatar
    ORDER BY
        clearance_count DESC
    LIMIT 10;
END;
$$ LANGUAGE plpgsql;

-- Create the get_user_clearances function
CREATE OR REPLACE FUNCTION get_user_clearances(p_user_id uuid)
RETURNS TABLE(callsign text, destination text, clearance_text text, created_at timestamptz) AS $$
BEGIN
    RETURN QUERY
    SELECT
        cg.callsign,
        cg.destination,
        cg.clearance_text,
        cg.created_at
    FROM
        clearance_generations cg
    WHERE
        cg.user_id = p_user_id
    ORDER BY
        cg.created_at DESC;
END;
$$ LANGUAGE plpgsql;
